version: "3"
services:
  monitoring:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: validators-monitoring
    volumes:
      - ./logs:/home/node/app/logs
  dns:
    - https://core.bloxberg.org
